name: Build to GCP

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - cicd/deploy

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}   # Proyecto GCP (secreto)
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}  # Bucket GCS (secreto)
 
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Debug node_modules
        run: |
          ls -la node_modules/@rollup || echo "@rollup not found"
          ls -la node_modules/@beetpack || echo "@beetpack not found"

      - name: Install dependencies
        run: |
          npm ci
          npm install @rollup/rollup-linux-x64-gnu --no-save

      - name: Build application
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  deploy:
    name: Deploy App to GCP
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Verify dist folder
        run: ls -la ./dist

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Upload to GCS Bucket
        run: |
          gsutil -m rsync -r -d ./dist ${{ env.GCS_BUCKET }}
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" ${{ env.GCS_BUCKET }}/**/*.js
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" ${{ env.GCS_BUCKET }}/**/*.css
          gsutil -m setmeta -h "Cache-Control:no-cache" ${{ env.GCS_BUCKET }}/index.html